apt-get update;
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -;
apt install -y nodejs;
apt-get install -y nginx vim uwsgi;
apt-get install -y uwsgi-plugin-python3;
apt-get install -y python3.8-venv;
python3 -m venv /var/www/garden-tracker/venv;
apt-get install -y python3-pip;
cd /var/www/garden-tracker;
touch garden-tracker.db;
source venv/bin/activate;
pip install -r requirements.txt;
python3 -c "from main import app_migrate;app_migrate()";
cp /var/www/garden-tracker/deployment/nginx.conf /etc/nginx/sites-enabled/default;
cp /var/www/garden-tracker/deployment/uwsgi.ini /etc/uwsgi/apps-enabled/garden-tracker.ini;
mkdir /var/log/garden;
cd /var/www/garden-tracker/quasar-project;
npm install -g npm@latest;
npm install -g @quasar/cli;
npm install;
quasar build;
service uwsgi restart;
service nginx restart;
